export const coolingTypes = ["Air Cooled", "Hydro", "Immersion"];
export const algorithm = [
  "Amoveo",
  "BCD",
  "BCX",
  "BMW512",
  "Blake (14r)",
  "Blake (2b)",
  "Blake (2b-BCHC)",
  "Blake (2b-Sia)",
  "Blake (2s)",
  "Blake (2s-Kadena)",
  "Blake3",
  "CryptoNight",
  "CryptoNightLite",
  "CryptoNightR",
  "Eaglesong",
  "Equihash",
  "Etchash",
  "Ethash",
  "Groestl",
  "Handshake",
  "KHeavyHash",
  "KangarooTwelve",
  "Keccak",
  "Keccak-C",
  "Keccak-D",
  "Keccak256",
  "LBRY",
  "Lyra2REv2",
  "Lyra2REv3",
  "Lyra2z",
  "Myr-Groestl",
  "NEXUS",
  "NexaPoW",
  "Nist5",
  "Odocrypt",
  "PHI1612",
  "Pascal",
  "Quark",
  "Qubit",
  "SHA-256",
  "SHA3x",
  "SHA512256d",
  "Scrypt",
  "Sha3d",
  "Skein",
  "Solidity-SHA3",
  "Tellor",
  "Tensority",
  "Tribus",
  "Veriblock",
  "X11",
  "X11Gost",
  "X13",
  "X14",
  "X15",
  "X17",
  "XDag",
  "ZP",
  "cuckAToo31",
  "cuckAToo32",
  "vBlake2",
  "zkSNARK",
  "0",
];
